### ISSUE TITLE
printImage Function Error

### ISSUE THREAD

**Issue by jeremy-hoot** [Klemen1337/node-thermal-printer#187]
Hello, when I print an image I am returned with this error: 

`
Error: Invalid file signature
    at module.exports.Parser._parseSignature (...\node_modules\pngjs\lib\parser.js:50:18)
    at module.exports.SyncReader.process (...\node_modules\pngjs\lib\sync-reader.js:34:17)
    at module.exports (...\node_modules\pngjs\lib\parser-sync.js:63:10)
    at Object.exports.read (...\node_modules\pngjs\lib\png-sync.js:10:10)
    at Star.printImage (...\node_modules\node-thermal-printer\lib\types\star.js:235:26)
    at ThermalPrinter.printImage (C..\node_modules\node-thermal-printer\lib\core.js:377:45)
    at print (...\index.js:20:6)
    at Object.<anonymous> (...\index.js:49:1)
`

the function I wrote looks like this: 

`
async function print() {
    await printMachine
    .printImage("./taconova.png")
    .catch((err) => console.log(err));
  try {
    printer.execute(function (err) {
      if (err) {
        console.log("printer failed: ", err);
      } else {
        console.log("successful");
      }
    });
  } catch (error) {
    console.log("error: ", error);
  }
}
`

Any help would be great.

**Comment by jeremy-hoot** [comment]
**Update:** I was sent an invalid png file and that's why I was getting this error. Making sure the image send was solid and had a transparent background helped.
