### ISSUE TITLE
net issue

### ISSUE THREAD

**Issue by boardyuk** [Klemen1337/node-thermal-printer#20]
I'm trying to connect to an Epson network printer however I'm getting the following error

>  PS D:\Development\test\print-test> node .\app.js
> net.js:641
>     throw new TypeError('invalid data');
>     ^
> 
> TypeError: invalid data
>     at Socket.write (net.js:641:11)
>     at Object.module.exports.execute (D:\Development\test\print-test\node_modules\node-thermal-printer\node-thermal-printer.js:35:15)
>     at Object.<anonymous> (D:\Development\test\print-test\app.js:15:9)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:441:10)
>     at startup (node.js:139:18)
>     at node.js:968:3

My JS
```
const printer = require("node-thermal-printer");

printer.init({
    type: "epson",
    characterSet: "UK",
    interface: '/dev/usb/lp0',
    ip: "192.168.100.252",
    port: 9100
});

printer.isPrinterConnected(function(response){
    console.log(response);
});

printer.execute();
```

Am I doing something wrong?

**Comment by boardyuk** [comment]
My fault, I didn't realise I needed to send data and couldn't just check for the existence of the printer.
