### ISSUE TITLE
write-file-queue\index.js:53:12。  [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

### ISSUE THREAD

**Issue by MzhouNiuniu** [Klemen1337/node-thermal-printer#216]
run    node examples/example.js

node:internal/fs/utils:675
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError[ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.open (node:fs:561:10)
    at Object.writeFile (node:fs:2185:6)
    at C:\Users\lill\Desktop\zy\node-thermal-printer\node_modules\.store\write-file-queue@0.0.1\node_modules\write-file-queue\index.js:53:12
    at Immediate.<anonymous> (C:\Users\lill\Desktop\zy\node-thermal-printer\node_modules\.store\dank-do-while@0.1.2\node_modules\dank-do-while\index.js:27:7)
    at process.processImmediate (node:internal/timers:476:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
�

**Comment by Klemen1337** [comment]
https://github.com/Klemen1337/node-thermal-printer#how-to-run-examples-set-to-epson
